//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDarPoolingMobile
{
    
    string HandleDarPoolingMobileRequest(Command c);
    
    Result GetMobileResult(string requestID);
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisterUserCommand))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InsertTripCommand))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchTripCommand))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(JoinCommand))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UnjoinCommand))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class Command
{
    
    private string commandIDField;
    
    private System.DateTime timestampField;
    
    private bool timestampFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string commandID
    {
        get
        {
            return this.commandIDField;
        }
        set
        {
            this.commandIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public System.DateTime timestamp
    {
        get
        {
            return this.timestampField;
        }
        set
        {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timestampSpecified
    {
        get
        {
            return this.timestampFieldSpecified;
        }
        set
        {
            this.timestampFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InsertErrorResult))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginErrorResult))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchTripResult))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UnjoinConfirmedResult))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisterOkResult))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ConnectionErrorResult))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginOkResult))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisterErrorResult))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(SearchTripError))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NullResult))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InsertOkResult))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class Result
{
    
    private string commentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string comment
    {
        get
        {
            return this.commentField;
        }
        set
        {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class InsertErrorResult : Result
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class LoginErrorResult : Result
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class SearchTripResult : Result
{
    
    private string originalQueryIDField;
    
    private Trip[] tripsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string originalQueryID
    {
        get
        {
            return this.originalQueryIDField;
        }
        set
        {
            this.originalQueryIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
    public Trip[] trips
    {
        get
        {
            return this.tripsField;
        }
        set
        {
            this.tripsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class Trip
{
    
    private System.DateTime arrivalDateTimeField;
    
    private bool arrivalDateTimeFieldSpecified;
    
    private string arrivalNameField;
    
    private double costField;
    
    private bool costFieldSpecified;
    
    private System.DateTime departureDateTimeField;
    
    private bool departureDateTimeFieldSpecified;
    
    private string departureNameField;
    
    private int freeSitsField;
    
    private bool freeSitsFieldSpecified;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private bool modifiableField;
    
    private bool modifiableFieldSpecified;
    
    private bool musicField;
    
    private bool musicFieldSpecified;
    
    private string notesField;
    
    private string ownerField;
    
    private bool smokeField;
    
    private bool smokeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime ArrivalDateTime
    {
        get
        {
            return this.arrivalDateTimeField;
        }
        set
        {
            this.arrivalDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ArrivalDateTimeSpecified
    {
        get
        {
            return this.arrivalDateTimeFieldSpecified;
        }
        set
        {
            this.arrivalDateTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string ArrivalName
    {
        get
        {
            return this.arrivalNameField;
        }
        set
        {
            this.arrivalNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public double Cost
    {
        get
        {
            return this.costField;
        }
        set
        {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CostSpecified
    {
        get
        {
            return this.costFieldSpecified;
        }
        set
        {
            this.costFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime DepartureDateTime
    {
        get
        {
            return this.departureDateTimeField;
        }
        set
        {
            this.departureDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DepartureDateTimeSpecified
    {
        get
        {
            return this.departureDateTimeFieldSpecified;
        }
        set
        {
            this.departureDateTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
    public string DepartureName
    {
        get
        {
            return this.departureNameField;
        }
        set
        {
            this.departureNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public int FreeSits
    {
        get
        {
            return this.freeSitsField;
        }
        set
        {
            this.freeSitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FreeSitsSpecified
    {
        get
        {
            return this.freeSitsFieldSpecified;
        }
        set
        {
            this.freeSitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IDSpecified
    {
        get
        {
            return this.idFieldSpecified;
        }
        set
        {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public bool Modifiable
    {
        get
        {
            return this.modifiableField;
        }
        set
        {
            this.modifiableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ModifiableSpecified
    {
        get
        {
            return this.modifiableFieldSpecified;
        }
        set
        {
            this.modifiableFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public bool Music
    {
        get
        {
            return this.musicField;
        }
        set
        {
            this.musicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MusicSpecified
    {
        get
        {
            return this.musicFieldSpecified;
        }
        set
        {
            this.musicFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
    public string Notes
    {
        get
        {
            return this.notesField;
        }
        set
        {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
    public string Owner
    {
        get
        {
            return this.ownerField;
        }
        set
        {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public bool Smoke
    {
        get
        {
            return this.smokeField;
        }
        set
        {
            this.smokeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SmokeSpecified
    {
        get
        {
            return this.smokeFieldSpecified;
        }
        set
        {
            this.smokeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class UnjoinConfirmedResult : Result
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class RegisterOkResult : Result
{
    
    private string registeredUsernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string registeredUsername
    {
        get
        {
            return this.registeredUsernameField;
        }
        set
        {
            this.registeredUsernameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class ConnectionErrorResult : Result
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class LoginOkResult : Result
{
    
    private string authorizedUsernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string authorizedUsername
    {
        get
        {
            return this.authorizedUsernameField;
        }
        set
        {
            this.authorizedUsernameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class RegisterErrorResult : Result
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class SearchTripError : Result
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class NullResult : Result
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class InsertOkResult : Result
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class User
{
    
    private System.DateTime birthDateField;
    
    private bool birthDateFieldSpecified;
    
    private string emailField;
    
    private string nameField;
    
    private string passwordHashField;
    
    private System.DateTime signupDateField;
    
    private bool signupDateFieldSpecified;
    
    private bool smokerField;
    
    private bool smokerFieldSpecified;
    
    private int userIDField;
    
    private bool userIDFieldSpecified;
    
    private string userNameField;
    
    private UserSex userSexField;
    
    private bool userSexFieldSpecified;
    
    private string whereaboutsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime BirthDate
    {
        get
        {
            return this.birthDateField;
        }
        set
        {
            this.birthDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BirthDateSpecified
    {
        get
        {
            return this.birthDateFieldSpecified;
        }
        set
        {
            this.birthDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string PasswordHash
    {
        get
        {
            return this.passwordHashField;
        }
        set
        {
            this.passwordHashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public System.DateTime SignupDate
    {
        get
        {
            return this.signupDateField;
        }
        set
        {
            this.signupDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SignupDateSpecified
    {
        get
        {
            return this.signupDateFieldSpecified;
        }
        set
        {
            this.signupDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public bool Smoker
    {
        get
        {
            return this.smokerField;
        }
        set
        {
            this.smokerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SmokerSpecified
    {
        get
        {
            return this.smokerFieldSpecified;
        }
        set
        {
            this.smokerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public int UserID
    {
        get
        {
            return this.userIDField;
        }
        set
        {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UserIDSpecified
    {
        get
        {
            return this.userIDFieldSpecified;
        }
        set
        {
            this.userIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
    public string UserName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public UserSex UserSex
    {
        get
        {
            return this.userSexField;
        }
        set
        {
            this.userSexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UserSexSpecified
    {
        get
        {
            return this.userSexFieldSpecified;
        }
        set
        {
            this.userSexFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
    public string Whereabouts
    {
        get
        {
            return this.whereaboutsField;
        }
        set
        {
            this.whereaboutsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="User.Sex", Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public enum UserSex
{
    
    /// <remarks/>
    f,
    
    /// <remarks/>
    m,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class QueryBuilder
{
    
    private System.DateTime arrivalDateTimeField;
    
    private bool arrivalDateTimeFieldSpecified;
    
    private string arrivalNameField;
    
    private double costField;
    
    private bool costFieldSpecified;
    
    private System.DateTime departureDateTimeField;
    
    private bool departureDateTimeFieldSpecified;
    
    private string departureNameField;
    
    private int freeSitsField;
    
    private bool freeSitsFieldSpecified;
    
    private bool musicField;
    
    private bool musicFieldSpecified;
    
    private string notesField;
    
    private string ownerField;
    
    private int rangeField;
    
    private bool rangeFieldSpecified;
    
    private bool smokeField;
    
    private bool smokeFieldSpecified;
    
    private System.DateTime timeField;
    
    private bool timeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime ArrivalDateTime
    {
        get
        {
            return this.arrivalDateTimeField;
        }
        set
        {
            this.arrivalDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ArrivalDateTimeSpecified
    {
        get
        {
            return this.arrivalDateTimeFieldSpecified;
        }
        set
        {
            this.arrivalDateTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string ArrivalName
    {
        get
        {
            return this.arrivalNameField;
        }
        set
        {
            this.arrivalNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public double Cost
    {
        get
        {
            return this.costField;
        }
        set
        {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CostSpecified
    {
        get
        {
            return this.costFieldSpecified;
        }
        set
        {
            this.costFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public System.DateTime DepartureDateTime
    {
        get
        {
            return this.departureDateTimeField;
        }
        set
        {
            this.departureDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DepartureDateTimeSpecified
    {
        get
        {
            return this.departureDateTimeFieldSpecified;
        }
        set
        {
            this.departureDateTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
    public string DepartureName
    {
        get
        {
            return this.departureNameField;
        }
        set
        {
            this.departureNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public int FreeSits
    {
        get
        {
            return this.freeSitsField;
        }
        set
        {
            this.freeSitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FreeSitsSpecified
    {
        get
        {
            return this.freeSitsFieldSpecified;
        }
        set
        {
            this.freeSitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public bool Music
    {
        get
        {
            return this.musicField;
        }
        set
        {
            this.musicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MusicSpecified
    {
        get
        {
            return this.musicFieldSpecified;
        }
        set
        {
            this.musicFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
    public string Notes
    {
        get
        {
            return this.notesField;
        }
        set
        {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
    public string Owner
    {
        get
        {
            return this.ownerField;
        }
        set
        {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public int Range
    {
        get
        {
            return this.rangeField;
        }
        set
        {
            this.rangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RangeSpecified
    {
        get
        {
            return this.rangeFieldSpecified;
        }
        set
        {
            this.rangeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public bool Smoke
    {
        get
        {
            return this.smokeField;
        }
        set
        {
            this.smokeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SmokeSpecified
    {
        get
        {
            return this.smokeFieldSpecified;
        }
        set
        {
            this.smokeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public System.DateTime time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool timeSpecified
    {
        get
        {
            return this.timeFieldSpecified;
        }
        set
        {
            this.timeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class RegisterUserCommand : Command
{
    
    private User newUserField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public User newUser
    {
        get
        {
            return this.newUserField;
        }
        set
        {
            this.newUserField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class InsertTripCommand : Command
{
    
    private Trip newTripField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public Trip newTrip
    {
        get
        {
            return this.newTripField;
        }
        set
        {
            this.newTripField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class SearchTripCommand : Command
{
    
    private QueryBuilder queryBuilderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public QueryBuilder queryBuilder
    {
        get
        {
            return this.queryBuilderField;
        }
        set
        {
            this.queryBuilderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class JoinCommand : Command
{
    
    private string passwordHashField;
    
    private string userNameField;
    
    private string passwordHashField1;
    
    private string usernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string PasswordHash
    {
        get
        {
            return this.passwordHashField;
        }
        set
        {
            this.passwordHashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string UserName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string passwordHash
    {
        get
        {
            return this.passwordHashField1;
        }
        set
        {
            this.passwordHashField1 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string username
    {
        get
        {
            return this.usernameField;
        }
        set
        {
            this.usernameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Communication")]
public partial class UnjoinCommand : Command
{
    
    private string userNameField;
    
    private string usernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string UserName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string username
    {
        get
        {
            return this.usernameField;
        }
        set
        {
            this.usernameField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="HandleDarPoolingMobileRequest", Namespace="http://tempuri.org/")]
public partial class HandleDarPoolingMobileRequestRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Command c;
    
    public HandleDarPoolingMobileRequestRequest()
    {
    }
    
    public HandleDarPoolingMobileRequestRequest(Command c)
    {
        this.c = c;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="HandleDarPoolingMobileRequestResponse", Namespace="http://tempuri.org/")]
public partial class HandleDarPoolingMobileRequestResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string HandleDarPoolingMobileRequestResult;
    
    public HandleDarPoolingMobileRequestResponse()
    {
    }
    
    public HandleDarPoolingMobileRequestResponse(string HandleDarPoolingMobileRequestResult)
    {
        this.HandleDarPoolingMobileRequestResult = HandleDarPoolingMobileRequestResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetMobileResult", Namespace="http://tempuri.org/")]
public partial class GetMobileResultRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string requestID;
    
    public GetMobileResultRequest()
    {
    }
    
    public GetMobileResultRequest(string requestID)
    {
        this.requestID = requestID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetMobileResultResponse", Namespace="http://tempuri.org/")]
public partial class GetMobileResultResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public Result GetMobileResultResult;
    
    public GetMobileResultResponse()
    {
    }
    
    public GetMobileResultResponse(Result GetMobileResultResult)
    {
        this.GetMobileResultResult = GetMobileResultResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DarPoolingMobileClient : Microsoft.Tools.ServiceModel.CFClientBase<IDarPoolingMobile>, IDarPoolingMobile
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://80.181.127.20:1155/Catania");
    
    public DarPoolingMobileClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public DarPoolingMobileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private HandleDarPoolingMobileRequestResponse HandleDarPoolingMobileRequest(HandleDarPoolingMobileRequestRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IDarPoolingMobile/HandleDarPoolingMobileRequest";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IDarPoolingMobile/HandleDarPoolingMobileRequestResponse";
        info.ResponseIsWrapped = true;
        HandleDarPoolingMobileRequestResponse retVal = base.Invoke<HandleDarPoolingMobileRequestRequest, HandleDarPoolingMobileRequestResponse>(info, request);
        return retVal;
    }
    
    public string HandleDarPoolingMobileRequest(Command c)
    {
        HandleDarPoolingMobileRequestRequest request = new HandleDarPoolingMobileRequestRequest(c);
        HandleDarPoolingMobileRequestResponse response = this.HandleDarPoolingMobileRequest(request);
        return response.HandleDarPoolingMobileRequestResult;
    }
    
    private GetMobileResultResponse GetMobileResult(GetMobileResultRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IDarPoolingMobile/GetMobileResult";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IDarPoolingMobile/GetMobileResultResponse";
        info.ResponseIsWrapped = true;
        GetMobileResultResponse retVal = base.Invoke<GetMobileResultRequest, GetMobileResultResponse>(info, request);
        return retVal;
    }
    
    public Result GetMobileResult(string requestID)
    {
        GetMobileResultRequest request = new GetMobileResultRequest(requestID);
        GetMobileResultResponse response = this.GetMobileResult(request);
        return response.GetMobileResultResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://tempuri.org/IDarPoolingMobile/HandleDarPoolingMobileRequest", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IDarPoolingMobile/HandleDarPoolingMobileRequest", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IDarPoolingMobile/GetMobileResult", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IDarPoolingMobile/GetMobileResult", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://tempuri.org/IDarPoolingMobile/HandleDarPoolingMobileRequestResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IDarPoolingMobile/HandleDarPoolingMobileRequestResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IDarPoolingMobile/GetMobileResultResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IDarPoolingMobile/GetMobileResultResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
