//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.IDarPooling")]
    public interface IDarPooling {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDarPooling/GetSimpleUsers", ReplyAction="http://tempuri.org/IDarPooling/GetSimpleUsersResponse")]
        Communication.SimpleUser[] GetSimpleUsers(Communication.SimpleUser[] inputUsers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDarPoolingChannel : Client.ServiceRef.IDarPooling, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DarPoolingClient : System.ServiceModel.ClientBase<Client.ServiceRef.IDarPooling>, Client.ServiceRef.IDarPooling {
        
        public DarPoolingClient() {
        }
        
        public DarPoolingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DarPoolingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DarPoolingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DarPoolingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Communication.SimpleUser[] GetSimpleUsers(Communication.SimpleUser[] inputUsers) {
            return base.Channel.GetSimpleUsers(inputUsers);
        }
    }
}
